### ISSUE TITLE
Just a small note regarding client configuration

### ISSUE THREAD

**Issue by madasha** [jeffkolez/websocket-demo#1]
The JS code in web/websocket.html (toggleConnect() function has the 192.168.56.101 IP address specified, which by default would not work for most people. I was able to get it running right away on my computer by replacing it with 127.0.0.1.

Thanks for the nice demo! After all, the gods of live demos were kind to you :)

**Comment by jeffkolez** [comment]
Thanks. I've (finally) added a textbox to each page for easier configuration.
